
name: flutter_private_chat
description: Chat privado cifrado para dos personas
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sodium: ^0.2.0
  web_socket_channel: ^3.0.3
  provider: ^6.1.1

flutter:
  uses-material-design: true
